const SQUARE_WIDTH = 24
const SQUARE_BORDER_WIDTH = 3
const PUZZLE_WIDTH = 10
const PUZZLE_HEIGHT = 20
const SIDEBAR_WIDTH = SQUARE_WIDTH * 6
const WAR_ZONE_WIDTH = PUZZLE_WIDTH * SQUARE_WIDTH

export const Config = Object.freeze({
  SQUARE_WIDTH,
  SQUARE_BORDER_WIDTH,
  PUZZLE_WIDTH,
  PUZZLE_HEIGHT,
  SIDEBAR_WIDTH,
  WAR_ZONE_WIDTH
})
