import { Square } from "../main/Square"

export const graphicGrid = [
  new Square({ row: 1, column: 1 }),
  new Square({ row: 2, column: 1 }),
  new Square({ row: 3, column: 1 }),
  new Square({ row: 3, column: 2 }),
  new Square({ row: 3, column: 4 }),
  new Square({ row: 3, column: 5 }),
  new Square({ row: 3, column: 6 }),
  new Square({ row: 2, column: 6 }),
  new Square({ row: 1, column: 6 }),
  new Square({ row: 1, column: 5 }),
  new Square({ row: 1, column: 4 }),
  new Square({ row: 2, column: 4 }),
  new Square({ row: 2, column: 8 }),
  new Square({ row: 1, column: 9 }),
  new Square({ row: 3, column: 9 }),
  new Square({ row: 3, column: 10 }),
  new Square({ row: 2, column: 10 }),
  new Square({ row: 5, column: 3 }),
  new Square({ row: 6, column: 3 }),
  new Square({ row: 6, column: 2 }),
  new Square({ row: 7, column: 3 }),
  new Square({ row: 8, column: 2 }),
  new Square({ row: 7, column: 1 }),
  new Square({ row: 5, column: 5 }),
  new Square({ row: 7, column: 5 }),
  new Square({ row: 8, column: 5 }),
  new Square({ row: 8, column: 7 }),
  new Square({ row: 7, column: 7 }),
  new Square({ row: 6, column: 7 }),
  new Square({ row: 6, column: 8 }),
  new Square({ row: 6, column: 9 }),
  new Square({ row: 7, column: 9 }),
  new Square({ row: 8, column: 9 }),
  new Square({ row: 10, column: 2 }),
  new Square({ row: 11, column: 1 }),
  new Square({ row: 12, column: 2 }),
  new Square({ row: 11, column: 3 }),
  new Square({ row: 12, column: 3 }),
  new Square({ row: 13, column: 3 }),
  new Square({ row: 14, column: 2 }),
  new Square({ row: 14, column: 5 }),
  new Square({ row: 14, column: 6 }),
  new Square({ row: 14, column: 7 }),
]
